/*
 * This source file was generated by the Gradle 'init' task
 */
package com.myankoi.kotlin

class App {
    fun setUser (name: String, age: Int) : Any {
        return "User $name with age $age"
    }
}

fun main() {
    val user = App().setUser("Rama", 20)

    println(user)
}
