/*
 * This source file was generated by the Gradle 'init' task
 */
package com.myankoi.kotlin

class App {
    var asemloy: String = "Kungkingkang"

    val greeting: String
        get() {
            return "Hai $asemloy"
        }


}

fun main() {
    println(App().greeting)
}
